baseurl = "/"
languageCode = "en-US"
title = "Zachary M Ford"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profilepic.jpeg"
  author = "Zach Ford"
  description = "Website about me"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "zachford8"
  Email         = "19zmf97@gmail.com"
  Twitter       = "zachford8"
  LinkedIn      = "zachary-ford-678b38174"
  Facebook      = "zach.ford.35"

## Main Menu
[[menu.main]]
  name = "About Me"
  identifier = "resume"
  weight = 300
  url = "/resume/"
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
