---
categories:
- resume
date: "2016-10-02T22:55:05-04:00"
showpagemeta: false
tags:
- resume
title: Resume
---

***

### EDUCATION
* **The University of Texas at Austin** (August 2017 - May 2020)
  + Bachelor of Arts and Science, Biology 
  + Minor: Business

* **Concordia University Texas** (August 2015 - April 2017)
  + Bachelor of Science, Biology

***

### EXPERIENCE
* **Robin Healthcare** -- *Senior Medical Scribe* ; Austin, TX (June 2019 - Present)
  + Accurately document medical visits and procedures as they are being performed by different medical providers across the
United States
  + Integrate provider dictations regarding imaging studies, lab results, procedural care, diagnoses, follow-up instructions, and
prescriptions into the clinical note
  + Navigate, maintain, and enter information into electronic medical record (EMR) databases 
  + Collaborate with a team to ensure the provider’s clinic is complete from start to finish

* **Luxury Boat Rentals** -- *Boat Rental Associate/Small Boat Captain* ; Austin, TX (May 2018 - August 2018)
  + Performed exceptional customer service to rental customers
  + Coordinated up to 14 watercrafts, ranging from 10ft to 30ft, ensuring each vessel was clean, fueled, and operationally harmless
  + Instructed customers on adequate operation of the vessel, including watercraft safety, directions, and caution signs 
  + Supervised up to 17 customers as small vessel captain

* **Twin Creeks Country Club** -- *Assistant Golf Professional* ; Cedar Park, TX (April 2016 - August 2018)
  + Illustrated exquisite professional customer service to all country club members and guests
  + Ensured 82 golf carts were clean and ready for use, while other daily tasks such as the driving range, parking lot, and communal areas were in pristine condition for member use
  + Handled appearance in the Golf Shop, concerning merchandise displays, restocking, and tagging
  + Aided in the management of department staff, including starter and member service attendants
  + Processed payments through a point-of-sale system for merchandise sales, green fees, and guest fees

***

### LEADERSHIP EXPERIENCE AND ACTIVITIES
* **Phi Kappa Psi** -- *Member* (August 2017 - May 2019)

* **Medical Shadowing Experience** (July 2017)
  + Observed Orthopedic, Oncology, Pediatric, and Anesthesiology specialists during clinical office hours
  + Witnessed Orthopedic and Ear Nose and Throat surgeons in different surgeries including total knee replacement,
arthroscopic shoulder surgery, arthroscopic knee surgery, and adenoid and tonsil removal 
  + Studied basic Anesthesiologist techniques in the operating room

***

### HONORS
* **University Honors**, The University of Texas at Austin (Spring 2018)
* **Deans List**, Concordia University Texas (Fall 2015 - Spring 2017)

***

### ADDITIONAL INFORMATION
* **Computer Skills**: MS Office (Word, Excel, PowerPoint), R/RStudio, G-Suite (Docs, Sheets, Slides), Python, SQL, HTML, CSS 

* **Certifications**: HIPAA Certification, Osha Certification, Texas Food Handler Certification, Boaters Safety License

* **Work Eligibility**: Eligible to work in the U.S. with no restrictions
  
***